# Generated by Django 6.0.6 on 2026-06-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIsoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('iso_code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('origin', models.TextField(default='')),
                ('forgetting_frequency', models.CharField(choices=[('FRQ', 'FREQUENT'), ('RAR', 'RARE'), ('NVR', 'NEVER')], max_length=3, null=True)),
                ('country_tags', models.ManyToManyField(related_name='definitions', to='dictApp.countryisocode')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('questions', models.ManyToManyField(to='dictApp.definition')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.language')),
            ],
            options={
                'unique_together': {('name', 'language')},
            },
        ),
        migrations.AddField(
            model_name='definition',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictApp.partofspeech'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.deck')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.definition')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.CharField(max_length=10)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('explanation', models.TextField()),
                ('custom_audio', models.FileField(upload_to='audio/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.definition')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictApp.source')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictApp.language')),
            ],
            options={
                'unique_together': {('name', 'language')},
            },
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.word'),
        ),
    ]
