# Generated by Django 6.0.6 on 2026-06-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryIsoCode',
            new_name='Country',
        ),
    ]
