# Generated by Django 6.0.6 on 2026-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0002_rename_countryisocode_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='part_of_speech',
        ),
        migrations.AddField(
            model_name='definition',
            name='part_of_speech',
            field=models.ManyToManyField(to='dictApp.partofspeech'),
        ),
    ]
