# Generated by Django 6.0.6 on 2026-06-18 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0003_remove_definition_part_of_speech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='part_of_speech',
        ),
        migrations.AddField(
            model_name='example',
            name='part_of_speech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictApp.partofspeech'),
        ),
    ]
