# Generated by Django 6.0.6 on 2026-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0004_remove_definition_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='forgetting_frequency',
            field=models.CharField(blank=True, choices=[('FRQ', 'FREQUENT'), ('RAR', 'RARE'), ('NVR', 'NEVER')], max_length=3, null=True),
        ),
    ]
