# Generated by Django 6.0.6 on 2026-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0005_alter_definition_forgetting_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_tags',
            field=models.ManyToManyField(related_name='languages', to='dictApp.country'),
        ),
    ]
