# Generated by Django 6.0.6 on 2026-06-20 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0006_language_country_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='country_tags',
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='countries', to='dictApp.language'),
        ),
        migrations.AlterField(
            model_name='example',
            name='custom_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='example',
            name='part_of_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictApp.partofspeech'),
        ),
    ]
