# Generated by Django 6.0.6 on 2026-06-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0007_remove_language_country_tags_country_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='dictApp.word'),
        ),
        migrations.AlterField(
            model_name='example',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictApp.definition'),
        ),
    ]
