# Generated by Django 6.0.6 on 2026-06-21 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0008_alter_definition_word_alter_example_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='source_category',
            field=models.CharField(blank=True, choices=[('MOV', 'MOVIE'), ('TVS', 'TVSHOW'), ('SON', 'SONG'), ('GAM', 'GAME'), ('BOK', 'BOOK'), ('OTH', 'OTHER')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('spotted_at', models.TimeField(blank=True, null=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.example')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.source')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='examples',
            field=models.ManyToManyField(related_name='sources', through='dictApp.Citation', to='dictApp.example'),
        ),
    ]
