# Generated by Django 6.0.6 on 2026-06-21 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0009_remove_example_source_source_source_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='added_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='citation',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='episode_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='released_year',
            field=models.IntegerField(default=1971),
            preserve_default=False,
        ),
    ]
