# Generated by Django 6.0.6 on 2026-06-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0010_rename_added_at_example_created_citation_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='origin',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
