# Generated by Django 6.0.6 on 2026-06-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0011_alter_definition_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='episode_name',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='season_number',
        ),
        migrations.AlterField(
            model_name='citation',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictApp.example'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictApp.source'),
        ),
        migrations.AlterField(
            model_name='example',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('episode_name', models.CharField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictApp.source')),
            ],
        ),
        migrations.AddField(
            model_name='citation',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictApp.episode'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('source__isnull', False), ('episode__isnull', False), _connector='OR'), name='citation_source_or_episode_required'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('source', 'season_number', 'episode_number')},
        ),
    ]
