# Generated by Django 6.0.6 on 2026-06-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0012_remove_citation_episode_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='country_tags',
            field=models.ManyToManyField(blank=True, related_name='definitions', to='dictApp.country'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image'),
        ),
        migrations.AlterField(
            model_name='source',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image'),
        ),
        migrations.AlterField(
            model_name='source',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
