# Generated by Django 6.0.6 on 2026-06-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0013_alter_definition_country_tags_alter_definition_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
