# Generated by Django 6.0.6 on 2026-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0014_source_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name', 'iso_code'), name='unique_name_iso'),
        ),
    ]
