# Generated by Django 6.0.6 on 2026-07-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0015_country_unique_name_iso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.language')),
            ],
            options={
                'unique_together': {('country', 'language')},
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='countries', through='dictApp.CountryLanguage', to='dictApp.language'),
        ),
    ]
