# Generated by Django 6.0.6 on 2026-07-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0016_countrylanguage_alter_country_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrylanguage',
            name='added_manually',
            field=models.BooleanField(default=False),
        ),
    ]
