# Generated by Django 6.0.6 on 2026-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0017_countrylanguage_added_manually'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrylanguage',
            name='added_manually',
        ),
        migrations.AddField(
            model_name='country',
            name='added_manually',
            field=models.BooleanField(default=False),
        ),
    ]
