# Generated by Django 6.0.6 on 2026-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0018_remove_countrylanguage_added_manually_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='in_user_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='is_idiom',
            field=models.BooleanField(default=False),
        ),
    ]
