# Generated by Django 6.0.6 on 2026-07-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0019_language_in_user_set_word_is_idiom'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='added_manually',
            field=models.BooleanField(default=False),
        ),
    ]
