# Generated by Django 6.0.6 on 2026-07-08 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0020_language_added_manually'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partofspeech',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_of_speech', to='dictApp.language'),
        ),
    ]
