# Generated by Django 6.0.6 on 2026-07-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0021_alter_partofspeech_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='google_ngram_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
