# Generated by Django 6.0.6 on 2026-07-13 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0022_language_google_ngram_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('SYN', 'SYNONYM'), ('ANT', 'ANTONYM')], max_length=3)),
                ('word_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dictApp.word')),
                ('word_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dictApp.word')),
            ],
            options={
                'unique_together': {('word_1', 'word_2')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='related_words',
            field=models.ManyToManyField(blank=True, related_name='+', through='dictApp.WordRelation', through_fields=('word_1', 'word_2'), to='dictApp.word'),
        ),
    ]
