# Generated by Django 6.0.6 on 2026-07-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0023_wordrelation_word_related_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrelation',
            name='category',
            field=models.CharField(blank=True, choices=[('SPT', 'Sports'), ('MNY', 'Money & Finance'), ('MED', 'Medicine & Health'), ('FOD', 'Food & Cooking'), ('TEC', 'Technology'), ('SCI', 'Science'), ('ART', 'Art & Literature'), ('MUS', 'Music'), ('POL', 'Politics & Government'), ('LAW', 'Law & Legal'), ('REL', 'Religion & Philosophy'), ('EDU', 'Education'), ('NAT', 'Nature & Animals'), ('TRV', 'Travel & Geography'), ('FAS', 'Fashion & Beauty'), ('MIL', 'Military & War'), ('SLG', 'Slang & Informal'), ('TAB', 'Taboo / Swear Words'), ('WRK', 'Work & Business'), ('FAM', 'Family & Relationships')], help_text='Topic domain of this relation', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='wordrelation',
            name='relation_type',
            field=models.CharField(choices=[('SYN', 'SIMILAR TO'), ('ANT', 'OPPOSITE TO'), ('CFW', 'CONFUSED WITH'), ('HPM', 'SOUND ALIKE')], max_length=3),
        ),
    ]
