# Generated by Django 6.0.6 on 2026-07-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0024_wordrelation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='examples',
        ),
        migrations.AlterField(
            model_name='source',
            name='released_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_category',
            field=models.CharField(choices=[('MOV', 'MOVIE'), ('TVS', 'TVSHOW'), ('SON', 'SONG'), ('GAM', 'GAME'), ('BOK', 'BOOK'), ('OTH', 'OTHER')], default='OTH', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordrelation',
            name='relation_type',
            field=models.CharField(choices=[('SYN', 'SIMILAR TO'), ('ANT', 'OPPOSITE TO'), ('CFW', 'CONFUSED WITH'), ('HPM', 'SOUND ALIKE'), ('CAT', 'SAME CATEGORY')], max_length=3),
        ),
    ]
