# Generated by Django 6.0.6 on 2026-07-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0025_remove_source_examples_alter_source_released_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('CHP', 'CHAPTER'), ('TRK', 'TRACK'), ('MIS', 'MISSION')], max_length=3)),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='citation_source_or_episode_required',
        ),
        migrations.AlterField(
            model_name='citation',
            name='spotted_at',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_category',
            field=models.CharField(choices=[('MOV', 'MOVIE'), ('TVS', 'TVSHOW'), ('SON', 'SONG'), ('ALB', 'ALBUM'), ('GAM', 'GAME'), ('BOK', 'BOOK'), ('OTH', 'OTHER')], max_length=3),
        ),
        migrations.AddField(
            model_name='segment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.source'),
        ),
        migrations.AddField(
            model_name='citation',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictApp.segment'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('source__isnull', False), ('episode__isnull', False), ('segment__isnull', False), _connector='OR'), name='a_source_is_required'),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('segment_type', 'name', 'number')},
        ),
    ]
