# Generated by Django 6.0.6 on 2026-07-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0026_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.PROTECT, to='dictApp.language'),
            preserve_default=False,
        ),
    ]
