# Generated by Django 6.0.6 on 2026-07-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0027_source_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode_name',
            new_name='name',
        ),
    ]
