# Generated by Django 6.0.6 on 2026-07-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0028_rename_episode_name_episode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='custom_audio',
        ),
        migrations.RemoveField(
            model_name='wordrelation',
            name='category',
        ),
        migrations.AddField(
            model_name='citation',
            name='custom_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='citation',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictApp.image'),
        ),
        migrations.AddField(
            model_name='definition',
            name='topic_category',
            field=models.CharField(blank=True, choices=[('SPT', 'Sports'), ('MNY', 'Money & Finance'), ('MED', 'Medicine & Health'), ('FOD', 'Food & Cooking'), ('TEC', 'Technology'), ('SCI', 'Science'), ('ART', 'Art & Literature'), ('MUS', 'Music'), ('POL', 'Politics & Government'), ('LAW', 'Law & Legal'), ('REL', 'Religion & Philosophy'), ('EDU', 'Education'), ('NAT', 'Nature & Animals'), ('TRV', 'Travel & Geography'), ('FAS', 'Fashion & Beauty'), ('MIL', 'Military & War'), ('SLG', 'Slang & Informal'), ('TAB', 'Taboo / Swear Words'), ('WRK', 'Work & Business'), ('FAM', 'Family & Relationships')], help_text='Topic domain of this relation', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.example'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
