# Generated by Django 6.0.6 on 2026-07-24 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0029_remove_example_custom_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='dictApp.source'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dictApp.source'),
        ),
    ]
