# Generated by Django 6.0.6 on 2026-07-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0030_alter_episode_source_alter_segment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='example',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='dictApp.example'),
        ),
    ]
