# Generated by Django 6.0.6 on 2026-07-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0031_alter_citation_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_type',
            field=models.CharField(choices=[('PRL', 'PROLOGUE'), ('CHP', 'CHAPTER'), ('EPL', 'EPILOGUE'), ('TRK', 'TRACK'), ('MIS', 'MISSION'), ('ACT', 'ACT')], max_length=3),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_category',
            field=models.CharField(choices=[('MOV', 'MOVIE'), ('TVS', 'TVSHOW'), ('SON', 'SONG'), ('ALB', 'ALBUM'), ('BOK', 'BOOK'), ('ABK', 'AUDIO BOOK'), ('POD', 'PODCAST')], max_length=3),
        ),
    ]
