# Generated by Django 6.0.6 on 2026-07-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0032_alter_segment_name_alter_segment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='number',
            field=models.IntegerField(),
        ),
    ]
