# Generated by Django 6.0.6 on 2026-08-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0033_alter_segment_name_alter_segment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_category',
            field=models.CharField(choices=[('MOV', 'Movie'), ('TVS', 'TV Show'), ('SON', 'Song'), ('ALB', 'Album'), ('BOK', 'Book'), ('ABK', 'Audio Book'), ('POD', 'Podcast')], max_length=3),
        ),
    ]
