# Generated by Django 6.0.6 on 2026-08-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0034_citation_page_alter_source_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='example',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
