# Generated by Django 6.0.6 on 2026-08-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0036_alter_definition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
