# Generated by Django 6.0.6 on 2026-08-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0037_alter_example_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
