# Generated by Django 6.0.6 on 2026-08-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0038_word_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='google_ngram_code',
        ),
        migrations.AddField(
            model_name='language',
            name='iso_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
