# Generated by Django 6.0.6 on 2026-08-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0039_remove_language_google_ngram_code_language_iso_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='questions',
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_questions', to='dictApp.deck')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.definition')),
                ('distractors', models.ManyToManyField(blank=True, related_name='distractor_in_deck_questions', to='dictApp.definition')),
            ],
            options={
                'unique_together': {('deck', 'definition')},
            },
        ),
    ]
