# Generated by Django 6.0.6 on 2026-08-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0040_remove_deck_questions_alter_deck_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='questions',
            field=models.ManyToManyField(related_name='decks_as_question', through='dictApp.DeckQuestion', to='dictApp.definition'),
        ),
    ]
