# Generated by Django 6.0.6 on 2026-09-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0041_deck_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckquestion',
            name='distractors',
            field=models.ManyToManyField(blank=True, related_name='distractor_in_deck_questions', to='dictApp.word'),
        ),
    ]
