# Generated by Django 6.0.6 on 2026-09-17 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0042_alter_deckquestion_distractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='language',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.PROTECT, to='dictApp.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citation',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='dictApp.episode'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='dictApp.segment'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='dictApp.source'),
        ),
    ]
