# Generated by Django 6.0.6 on 2026-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0043_deck_language_alter_citation_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
